[[chapter_elliptic_curve cryptography]]
== Elliptic Curve Cryptography

The previous two chapters covered some fundamental math. We learned how Finite Fields work and we also learned what an Elliptic Curve is. In this chapter, we're going to combine the two concepts to get Elliptic Curve Cryptography. Specifically, we're going to build the primitives needed to sign and verify messages, which is at the heart of what Bitcoin does.

=== Elliptic Curves over Reals

We discussed in the last chapter what an Elliptic curve looks like visually because we were plotting the curve over *real* numbers. Specifically, it's not just integers or even rational numbers, but all *real* numbers. Pi, sqrt(2), e+7th root of 19, etc are all part of real numbers.

What's interesting is that *real* numbers are also a field. Note unlike a *finite* field, there are an infinite number of real numbers, but otherwise the same properties hold:

* if *a* and *b* are in the set, *a+b* and *a⋅b* is in the set. We call this property _closed_
* if *a* is in the set, *-a* is in the set, or what we call the _additive inverse_.
* if *a* is in the set and is not 0, *a^-1^* is in the set, or what we call the _multiplicative inverse_.

Clearly, all of these are true as normal addition and multiplication apply for the first part, -x applies for the second part and 1/x applies for the third part.

The nice thing about real numbers is that we can easily plot what's going on and see the whole thing visually as we did in the last chapter. For example, y^2^=x^3^+7 can be plotted like this:

TODO: graph of secp256k1 curve

What's interesting is that we can use this equation over any field, including the Finite Fields we explored in Chapter 1. The only difference is that we have to use the addition/subtraction/multiplication/division as we defined them, not the "normal" versions that the real numbers use.

=== Elliptic Curves over Finite Fields

For example, we can see what to do for the equation y^2^=x^3^+7 over F~103~. Let's see if the point (17,64) is on the curve:

64^2^%103=79
(17^3^+7)%103=79

Indeed, that point is on the curve using the Finite Field math.

Because we're evaluating the equation over a Finite Field, the plot of the equation looks vastly different:

TODO: graph of secp256k1 curve over finite field

As you can see, it's very much a scattershot of points and there's no smooth curve here. This is not surprising since the points are discrete.

What's important here to realize is that we can evaluate the same equation using the addition, subtraction, multiplication, division and exponentiation as we defined them for Finite Fields and everything still works. This may seem surprising, but abstract math has regularities like this despite being different than the traditional modes of calculation you may be familiar with.

==== Exercise {counter:exercise}

Evaluate whether these points are on the curve y^2^=x^3^+7 over F~223~

(192,105), (17,56), (200,119), (1,193), (42,99)

=== Coding Elliptic Curves over Finite Fields

Because we defined an Ellptic curve point and utilize the +,-,* and / operators for Finite Fields, we can actually just combine the two classes to evaluate Elliptic Curve Points over a Finite Field.

[source,python]
----
a = FieldElement(num=0, prime=223)
b = FieldElement(num=7, prime=223)
x = FieldElement(num=192, prime=223)
y = FieldElement(num=105, prime=223)

p1 = Point(x, y, a, b)
----

When initializing `Point`, we will run through this part of the code:

[source,python]
----
class Point:

    def __init__(self, x, y, a, b):
        self.a = a
        self.b = b
        self.x = x
        self.y = y
        if self.y$$**$$2 != self.x$$**$$3+self.a*self.x + self.b: # <1>
	    raise ValueError('Point ({},{}) is not on the curve where a,b={},{}'.format(x,y,a,b))
----
<1> Check to see whether the point is on the curve.

The addition (+), exponentiation (**) and equality (==) here will end up utilizing the $$__add__$$, $$__pow__$$ and $$__eq__$$ methods from `FiniteField` respectively and _not_ the integer equivalents. As we will see, being able to do the same equation but with different definitions for the basic arithemtic operators is what will allow us to construct an Elliptic Curve Cryptography library.

==== Exercise {counter:exercise}

Write a test called test_on_curve that tests whether the points from the previous exercise over the curve y^2^=x^3^+7 over F~223~ are valid or not.

=== Point Addition over Finite Fields

We can use all the same equations over finite fields, including the linear equation:

y=mx+b

It turns out that a "line" in a finite field is not quite what you'd expect, either:

TODO: graph of a line over a finite field

Still, the equation works and we can calculate what y should be for a given x.

Remarkably, point addition works over finite fields as well. This is because the elliptic curve and line equations still work! The same exact formulas we used to calculate Point Addition over Reals work just as well over Finite Fields. Specifically:

when x~1~≠x~2~

P~1~=(x~1~,y~1~), P~2~=(x~2~,y~2~), P~3~=(x~3~,y~3~)

P~1~+P~2~=P~3~

s=(y~2~-y~1~)/(x~2~-x~1~)

x~3~=s^2^-x~1~-x~2~

y~3~=s(x~1~-x~3~)-y~1~

when P~1~=P~2~

P~1~=(x~1~,y~1~), P~3~=(x~3~,y~3~)

P~1~+P~1~=P~3~

s=(3x~1~^2^+a)/(2y~1~)

x~3~=s^2^-2x~1~

y~3~=s(x~1~-x~3~)-y~1~

All of the equations for Elliptic Curves work over Finite Fields and that sets us up to create some Cryptographic primitives.

==== Coding Point Addition over Finite Fields

Because we coded FieldElement in such a way as to define $$__add__$$, $$__sub__$$, $$__mul__$$, $$__truediv__$$ and $$__pow__$$, we can simply initialize `Point` with `FieldElement` objects and point addition will work:

[source,python]
----
a = FieldElement(num=0, prime=223)
b = FieldElement(num=7, prime=223)
x1 = FieldElement(num=192, prime=223)
y1 = FieldElement(num=105, prime=223)
x1 = FieldElement(num=17, prime=223)
y1 = FieldElement(num=56, prime=223)

p1 = Point(x1, y1, a, b)
p2 = Point(x2, y2, a, b)

print(p1+p2)
----

==== Exercise {counter:exercise}

For the curve y^2^=x^3^+7 over F~223~, find:

(170,142) + (60,139)
(47,71) + (17,56)
(143,98) + (76,66)

==== Exercise {counter:exercise}

Write unit tests to test point addition

=== Scalar multiplication for Elliptic Curves

Because we can add a point to itself, we can introduce some new notation:

(170,142) + (170,142) = 2*(170,142)

Similarly, because we have associativity, we can actually add the point again:

2*(170,142) + (170,142) = 3*(170, 142)

We can actually do this as many times as we want. This is what we call Scalar Multiplication. That is, we have a _scalar_ number in front of the point. We can do this because we have defined point addition.

What's interesting about scalar multiplication is that it's really hard to predict without actually calculating:

TODO: graph of where the point ends up when scalar is 2, 10, 17, etc

This is because point addition is non-linear. That is, not easy to calculate. In fact, doing the scalar multiplication is more or less straightforward, but doing the opposite, scalar division, is not.

This is called the Discrete Log problem and is the basis of Elliptic Curve Cryptography.

The interesting thing about Scalar Multiplication is that at a certain number, we get to the point at infinity (remember, point at infinity is a lot like zero). If we imagine a point G and scalar multiply until we get the point at infinity, we end up with a set like this:

{ G, 2G, 3G, 4G, ... nG }

It turns out that this set is called a Group and because n is finite, we have a Finite Group. Groups are interesting mathematically because they behave a lot like addition:

G+4G=5G or aG+bG=(a+b)G

When we combine the fact that scalar multiplication is easy to go in one direction but hard in the other and the mathematical properties of a Group, we have exactly what we need for Elliptic Curve Cryptography.

.Why is this called the Discrete Log Problem?
****
You may be wondering why the problem of scalar *multiplication* is referred to as the discrete *log* problem.

We called the operation between the points "addition", but we could easily have called it a point "operation". Typically, a new operation that you define in math utilizes the dot operator (⋅). The dot operator is also used for multiplication, and it sometimes helps to think that way:

P~1~⋅P~2~=P~3~

When you do lots of multiplying, that's the same as exponentiation. Scalar multiplication when we called it "point addition" becomes scalar exponentiation:

P^7^=Q

The discrete log problem is really the ability to reverse this:

log~P~Q=7

The log equation on the left is not analytically calculatable. That is, there is no known formula that you can plug in to get the answer generally. This is all a bit confusing, but it's fair to say that we could call the problem the "Discrete Scalar Division" problem instead of Discrete Log.
****

=== Mathematical Groups

Unlike fields, groups have only a single operation. In our case, Point Addition is our operation. We also have a few other properties like closure, invertibility, commutativity and associativity. Lastly, we need the identity.

It turns out that we have all of these things with Point Addition. Let's look at each property

==== Closure

This is perhaps the easiest to prove since we generated the group in the first place by adding G over and over. Thus, two different elements look like this:

aG + bG

We know that the result is going to be:

(a+b)G

How do we know if this element is in the group? If a+b < n, then we know it's in the group by definition. If a+b >= n, then we know a < n and b < n, so a+b<2n so a+b-n<n.

(a+b-n)G=aG+bG-nG=aG+bG-O=aG+bG

So we know that this element is in the group, proving closure.

==== Invertibility

Visually, invertibility is easy to see:

TODO: show graph of points on opposite sides of the x-axis

Mathematically, we know that if aG is in the group, (n-a)G is also in the group. You can add them together to get 0.

==== Commutativity

Again, this is very easy to see visually:

TODO: show that points can reverse order

The equations for figuring out the third point also make this clear:

P~1~=(x~1~,y~1~), P~2~=(x~2~,y~2~), P~3~=(x~3~,y~3~)

x~3~=s^2^-x~1~-x~2~

y~3~=s(x~1~-x~3~)-y~1~=s(x~2~-x~3~)-y~2~

You can swap P~1~ and P~2~ to get the exact same equation.

==== Associativity

This is the hardest to prove but can be seen visually:

TODO: show that (A+B)+C=A+(B+C)

Mathematically, this is a bit more involved.



=== Defining the curve for Bitcoin

It turns out that we can choose much larger primes than we've been using. 
