# tag::exercise1[]
==== Exercise 1

Write the corresponding method $$__ne__$$ which checks if two `FieldElement` objects are _not equal_ to each other.
# end::exercise1[]
# tag::exercise2[]
==== Exercise 2

Solve these problems in F~57~ (assume all +'s here are +~f~ and -`s here -~f~)

. 44+33
. 9-29
. 17+42+49
. 52-30-38
# end::exercise2[]
# tag::exercise3[]
==== Exercise 3

Write the corresponding $$__sub__$$ method which defines the subtraction of two field elements.
# end::exercise3[]
# tag::exercise4[]
==== Exercise 4

Solve the following equations in F~97~ (again, assume ⋅ and exponentiation are field versions):

. 95⋅45⋅31
. 17⋅13⋅19⋅44
. 12^7^⋅77^49^
# end::exercise4[]
# tag::exercise5[]
==== Exercise 5

For k = 1, 3, 7, 13, 18, what is this set in F~19~?

{k⋅0, k⋅1, k⋅2, k⋅3, ... k⋅18}

Do you notice anything about these sets?
# end::exercise5[]
# tag::exercise6[]
==== Exercise 6

Write the corresponding $$__mul__$$ method which defines the multiplication of two field elements.
# end::exercise6[]
# tag::exercise7[]
==== Exercise 7

For p = 7, 11, 17, 31, 43, what is this set in F~p~?

{1^(p-1)^, 2^(p-1)^, 3^(p-1)^, 4^(p-1)^, ... (p-1)^(p-1)^}
# end::exercise7[]
# tag::exercise8[]
==== Exercise 8

Solve the following equations in F~31~:

* 3 / 24
* 17^-3^
* 4^-4^⋅11
# end::exercise8[]
# tag::exercise9[]
==== Exercise {counter:exercise}

Write the corresponding $$__truediv__$$ method which defines the division of two field elements.

Note that in Python3, division is separated into $$__truediv__$$ and $$__floordiv__$$. The first does normal division, the second does integer division.
# end::exercise9[]

